export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";
export const COMMENT_SUBMITTING = "COMMENT_SUBMITTING";

export const LOAD_DISHES = "LOAD_DISHES";
export const DISHES_LOADING = "DISHES_LOADING";
export const LOAD_DISHES_ERROR = "LOAD_DISHES_ERROR";

export const LOAD_COMMENT = "LOAD_COMMENT";
export const COMMENT_LOADING = "COMMENT_LOADING";
export const LOAD_COMMENT_ERROR = "LOAD_COMMENT_ERROR";
